# Your Solution
services:
  book_catalog:
    image: 7p2sit722.azurecr.io/book_catalog:1
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    platform: linux/amd64
    ports:
    - "8000:8000"
    environment: 
    - DATABASE_URL=postgresql://sit722_7_2p_ilyx_user:8CXeZzKDZuLbjDOqKHrGf1bofQJ5d8po@dpg-cs3hd53v2p9s73eftnt0-a.oregon-postgres.render.com/sit722_7_2p_ilyx

  inventory_management:
    image: 7p2sit722.azurecr.io/inventory_management:1
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    platform: linux/amd64
    ports:
      - "8001:8001"
    environment: 
     - DATABASE_URL=postgresql://sit722_7_2p_ilyx_user:8CXeZzKDZuLbjDOqKHrGf1bofQJ5d8po@dpg-cs3hd53v2p9s73eftnt0-a.oregon-postgres.render.com/sit722_7_2p_ilyx
